---
- name: Install Apache
  yum: name=httpd24
  notify: restart httpd
  when: env == "aws"

- name: Install Apache
  yum: name=httpd
  notify: restart httpd
  when: env == "local"

- name: restart httpd
  service: name=httpd state=started enabled=yes
