# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  src = "../<%= themeName %>"
  dest = "/var/www/html/wordpress/wp-content/themes/<%= themeName %>"

  config.vm.define "dev" do |dev|
    dev.vm.box = "<%= vagrantBox %>"
    dev.vm.box_url = "(virtualbox,"
    dev.vm.network "private_network", ip: <%= vagrantIp %>
    # dev.vm.synced_folder src, dest, group: "apache", owner: "apache"

    dev.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/playbook.yml"
      ansible.sudo = false
      ansible.extra_vars = {
        env: "local",
        owner: "vagrant"
      }
    end
  end

  config.vm.define "pro" do |pro|

    pro.vm.box = "dummy"
    pro.vm.box_url = "(aws,"
    pro.vm.synced_folder src, dest, type: "rsync", rsync__exclude: ".git/"

    pro.vm.provider :aws do |aws, override|
      aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
      aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
      aws.keypair_name = ENV['AWS_KEYPAIR_NAME']

      aws.instance_type = "t2.micro"
      aws.region = "ap-northeast-1"

      aws.ami = "ami-e79cc4e6"

      aws.security_groups = ['vagrant']
      # aws.elastic_ip = true

      aws.tags = {'Name' => 'vagrant-wordpress'}

      override.ssh.username = 'ec2-user'
      override.ssh.private_key_path = ENV['AWS_PRIVATE_KEY_PATH']
    end

    pro.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/playbook.yml"
      ansible.sudo = false
      ansible.extra_vars = {
        env: "aws",
        owner: "ec2-user"
      }
    end

  end
end

